name: Static Code Analysis

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      - name: Install Composer dependencies
        run: |
          ddev start
          ddev composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          ddev composer install

      - name: Run static code analysis
        run: ddev composer ci:sca

      - uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        name: Annotate PHP CS Fixer
        if: always()
        with:
          files: php-cs-fixer.xml
          notices-as-warnings: true

      - uses: staabm/annotate-pull-request-from-checkstyle-action@v1
        name: Annotate PHPStan
        if: always()
        with:
          files: phpstan.xml
          notices-as-warnings: true
